# Changes to this file will NOT be reloaded in jekyll --watch mode! Restart
# jekyll after updating this file!

title: KasimirJS
description: educational grade development tools
google_analytics:
show_downloads: true

# Make directory-style links
permalink: pretty
#exclude: ['assets']

sass:
  sass_dir: _sass_disabled

page:
  type: article
  publisher: leanea Consulting
  site_name: leanea.de
  url: "https://leanea.de"
  icon_path: "https://static.leanea.de/uni-v3.0/assets/leanea"


livereload: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

  # /index/ path will be mounted to /
  - scope:
      path: "index"
    values:
      permalink: /

plugins:
- jekyll-optional-front-matter
